// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ssG702JLlU4KQZDaQLHNRifLY7SIHkc',
    appId: '1:4493924600:web:a4b8a674cfb84f49fd030d',
    messagingSenderId: '4493924600',
    projectId: 'algeneal-166f0',
    authDomain: 'algeneal-166f0.firebaseapp.com',
    storageBucket: 'algeneal-166f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZoWYtVGEuemcuWUhX1DKt1xyS8OD4Ito',
    appId: '1:4493924600:android:29756b81cf60276ffd030d',
    messagingSenderId: '4493924600',
    projectId: 'algeneal-166f0',
    storageBucket: 'algeneal-166f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKvnog6WYT2sxO2Bix5v_0PNpClXpbirQ',
    appId: '1:4493924600:ios:01b3b011ac317c36fd030d',
    messagingSenderId: '4493924600',
    projectId: 'algeneal-166f0',
    storageBucket: 'algeneal-166f0.firebasestorage.app',
    iosBundleId: 'com.example.aplicationAlgebraLineal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKvnog6WYT2sxO2Bix5v_0PNpClXpbirQ',
    appId: '1:4493924600:ios:01b3b011ac317c36fd030d',
    messagingSenderId: '4493924600',
    projectId: 'algeneal-166f0',
    storageBucket: 'algeneal-166f0.firebasestorage.app',
    iosBundleId: 'com.example.aplicationAlgebraLineal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-ssG702JLlU4KQZDaQLHNRifLY7SIHkc',
    appId: '1:4493924600:web:8dddc397fea6bad7fd030d',
    messagingSenderId: '4493924600',
    projectId: 'algeneal-166f0',
    authDomain: 'algeneal-166f0.firebaseapp.com',
    storageBucket: 'algeneal-166f0.firebasestorage.app',
  );
}
